### PR TITLE
Update new mods for SMAPI 2.0, enable update checks

### PR DESCRIPTION
**Pull request by Pathoschild**
This pull request...
* Updates StardustCore and SimpleSoundManager for SMAPI 2.0 compatibility.
* Enables update checks for all mods in SMAPI 2.0+.
* Updates the mod build package to 2.0 (which simplifies copying the mod into the `Mods` folder).
* Adds a readme for SimpleSoundManager.
* Fixes a few minor code issues.
* Bumps all versions for release.

If the changes look fine, can you deploy the following?

release zip | mod page
----------- | --------
[AutoSpeed 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377120/AutoSpeed.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/443)
[BillboardAnywhere 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377121/BillboardAnywhere.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/492)
[BuildEndurance 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377122/BuildEndurance.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/445)
[BuildHealth 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377123/BuildHealth.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/446)
[BuyBackCollectables 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377124/BuyBackCollectables.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/507)
[CustomShopsRedux 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377125/CustomShopsRedux.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/1378)
[DailyQuestAnywhere 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377126/DailyQuestAnywhere.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/513)
[Fall28SnowDay 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377127/Fall28SnowDay.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/486)
[HappyBirthday 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377110/HappyBirthday.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/520)
[MoreRain 1.5.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377111/MoreRain.1.5.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/441)
[MuseumRearranger 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377112/MuseumRearranger.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/428)
[NightOwl 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377113/NightOwl.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/433)
[NoMorePets 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377114/NoMorePets.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/506)
[SaveAnywhere 2.6.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377115/SaveAnywhere.2.6.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/444)
[SaveBackup 1.3.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377116/SaveBackup.1.3.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/444)
[SimpleSoundManager 1.0.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377117/SimpleSoundManager.1.0.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/1410)
[StardewSymphony 1.4.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377118/StardewSymphony.1.4.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/425)
[TimeFreeze 1.2.1.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1377119/TimeFreeze.1.2.1.zip) | [Nexus](https://nexusmods.com/stardewvalley/mods/973)

### CODE REVIEW

**Comment by janavarro95** [comment]
Looks good! Hopefully when the school term isn't so crazy I'll be able to mod again.

**Comment by Pathoschild** [comment]
Thanks! Since I have still access to the Nexus pages, I can deploy these for you if you have no objections.

**Comment by janavarro95** [comment]
Yup, that's part of the reason I left you as a colaborator just incase
something like this would happen. If you could do that, that would be
wonderful! :)

**Comment by Pathoschild** [comment]
All done except [Custom Shops Redux](https://www.nexusmods.com/stardewvalley/mods/1378) and [Simple Sound Manager](https://www.nexusmods.com/stardewvalley/mods/1410), which I don't have access to.

**Comment by janavarro95** [comment]
Ok, you should have access to the nexus pages for those mods too now! Thanks again!

**Comment by Pathoschild** [comment]
Updated Custom Shops Redux, but don't have access to [Simple Sound Manager](https://www.nexusmods.com/stardewvalley/mods/1410) yet.

**Comment by Pathoschild** [comment]
@janavarro95 SMAPI 2.0 released today, so the version of Simple Sound Manager on Nexus no longer works. If you can give me access to that mod too, I'll deploy the update. :)

**Comment by janavarro95** [comment]
Done and done! You should have access to simple sound manager now. I'll
have to take a peek at SMAPI 2.0. Anything super notable I should know of,
or a link to the new features?

**Comment by Pathoschild** [comment]
Simple Sound Manager updated!

The [SMAPI 2.0 release page](https://github.com/Pathoschild/SMAPI/releases) includes release highlights and links to more info, and the [SMAPI reference](https://stardewvalleywiki.com/Modding:SMAPI_APIs) is updated for 2.0.

**Pull request merged**
