### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by Pathoschild**
This pull request mainly...

* Removes build output from Git.
  _Build output should generally be ignored, because Git doesn't handle binary data very well which quickly impacts the repository size and performance. Since build output can be regenerated by just compiling the code, there's no need to keep it in source control._
* Removes some unused files.
* Simplifies the `.gitattributes` and `.gitignore` files.

Split from #6.

### CODE REVIEW

**Comment by janavarro95** [comment]
Ok, finally did it this time! Thanks for all of your help!

**Comment by Valamyr** [comment]
Im sure its my fault for clicking somewhere wrong but is there an easy way
to unsuscribe to this feed? Only if its no trouble.. I love Stardew and its
modding community but I'm getting CC'd pretty often lately on stuff I
couldn't possibly help with or understand, I'm just a end user. :)

**Comment by janavarro95** [comment]
There might be a way to turn off notifications for this repository somewhere. Otherwise I'm not sure myself. Maybe unstar this repository? I'm going to doing g a lot of updates so there will inevitably be a lot of notifications.

**Comment by Pathoschild** [comment]
@Valamyr Yep, click this option in the top-right corner:
>

**Comment by Valamyr** [comment]
No worries I think I know how to mute it. Thx for your hard work!!

**Pull request merged**
