### PR TITLE
Add screenreader accessibility support to the BirthdayMenu.

### PR DESCRIPTION
**Pull request by conundrum9999**
* Added optional dependency on shoaib.stardewaccess to provide screenreader accessibility for the blind (https://github.com/khanshoaib3/stardew-access)
* Load Stardew-access in HappyBirthdayModCore if available
* Update BirthdayMenu to enable keyboard navigation and speak selections if Stardew-access was loaded.
* Add translation strings where necessary.

### CODE REVIEW

**Comment by janavarro95** [comment]
Hi there, thanks so much for this pull request to add accessibility to the Happy Birthday mod! I promise I'll try to prioritize reading this pull request as part of my task list this week, I've only been able to just sit down in almost two weeks to get back into modding myself so hopefully I can catch up with my todo list and make this part of it. Thanks! :)

**Review by janavarro95 — APPROVED** [review]
Alrighty, this looks fine to me. The code looks good, is well commented, and from the Youtube videos describing the source mod I can approve this change. Thank you!

**Comment by janavarro95** [comment]
So I just updated the main download on nexus mods for Stardust Core, Happy Birthday, and the English Content pack, so hopefully that should be all the changes necessary for this pull request. Let me know if you need anything else. Thanks!

**Comment by conundrum9999** [comment]
Awesome thanks for getting this in so fast! I chose this mod because it seemed like a simple change to accomplish what I needed (giving my partner a break from setting my birthday every save...) as well as being simple in the sense of what I needed to change to make it work. I haven't tried all of your mods out yet so there might be others that could use help. I'll let you know as I find them. Happy to test.

**Pull request merged**
